# name : 'Hello World'
# # description: 'Greet someone and record the time'
# description: 'Greet someone'
# inputs:
#   who-to-greet:
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
#   # time:
#   #   description: 'The time we greeted you'
# runs:
#   # using: 'node16'
#   # main: 'index.js'
#   # using: 'docker'
#   # image: 'Dockerfile'
#   # args:
#   #   - ${{ inputs.who-to-greet }}
#   using: "composite"
#   steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
#     - id: random-number-generator
#       run: echo "::set-output name=random-number::$(echo $RANDOM)"
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash
#     - run: goodbye.sh
#       shell: bash


name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  time:
    value: ${{ steps.goodbye.outputs.time }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }} from playground.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ls
      shell: bash
    - id: goodbye
      run: ./goodbye.sh ${{ inputs.who-to-greet }}
      shell: bash
