on: 
  workflow_call:
    # secrets:
    #   superSecret:
    #     required: true
jobs:
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     # - name: Checkout
  #     #   uses: actions/checkout@v3
  #     # - name: Hello world action step
  #     #   uses: ./
  #     #   id: hello
  #     #   with:
  #     #     who-to-greet: 'Mona the Octocat'
  #     # - name: Get the output time
  #     #   run: echo "The time was ${{ steps.hello.outputs.time }}"
  #     - uses: actions/checkout@v3
  #     - id: foo
  #       uses: actions/hello-world-composite-action@v1
  #       with:
  #         who-to-greet: 'Mona the Octocat'
  #     - run: echo random-number ${{ steps.foo.outputs.random-number }}
  #       shell: bash
  reuse_work_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alist: [thing1, thing2, thing3]
        secondlist: [second1, second2, second3, second4]
    steps:
      - id: foo
        uses: jordan-van-dyk-form3/composite@main
        with:
          who: ${{ github.event.inputs.a_name }}
          something-neat: ${{ matrix.alist }}